services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: nba
      POSTGRES_PASSWORD: nba
      POSTGRES_DB: nba
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: ["11434:11434"]
    volumes:
      - ollamavol:/root/.ollama
    healthcheck:
      test: ["CMD", "sh", "-c", "ollama list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 30

  app:
    build: .
    environment:
      DB_DSN: postgresql://nba:nba@db:5432/nba
      OLLAMA_HOST: http://ollama:11434
      EMBED_MODEL: nomic-embed-text
      LLM_MODEL: llama3.2:3b
    depends_on:
      db:
        condition: service_started
      ollama:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./part1:/app/part1
      - ./backend:/app/backend
    ports: ["8000:8000"]
    command: >
      sh -c "uvicorn app.server:app
             --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
  ollamavol:
